[project]
name = "camilo-camilo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.1",
    "bs4>=0.0.2",
    "pandas>=2.3.3",
    "requests>=2.32.5",
]
